import type { NextPage } from 'next';
import Head from 'next/head';
import { Card } from '../components/card';

export async function getServerSideProps(_context: any) {
  return {
    props: {},
  };
}

const Home: NextPage = () => {
  return (
    <div className='h-[85vh]'>
      <Head>
        <title>Instituto Porto Alegre</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col text-center items-center h-full justify-center'>
        <h1 className='text-7xl mb-20'>Instituto Porto Alegre</h1>
        {/* <Image className='rounded-xl' src="/salvador.jpg" alt="Imagem de Jesus Cristo" width={600} height={350} /> */}
        <div className='flex'>
          <Card
            name='Links de acesso'
            link='/links'
            description='Links de todas as aulas do instituto'
          />
          <Card
            name='Matricula'
            link='https://docs.google.com/forms/d/e/1FAIpQLSd0y43FbhjFRI62qL42DezLBjtwC6nhubskd_JVlxH3js4hbw/viewform'
            description='Formulario de matricula do Instituto'
          />
          <Card
            name='Sobre'
            link='https://keysijones.vercel.app'
            description='Informacoes sobre o desenvolvedor'
          />
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
